### ISSUE TITLE
Error running the Environment rc

### ISSUE THREAD

**Issue by opogc** [matrix-io/matrix-creator-quickstart#20]
I am getting the following error when running the rc environment on the Raspberry Pi.

root@raspberrypi:/home/pi/matrix-os# NODE_ENV=rc node index.js
Environment Selected: rc
Loading Core Matrix Files
Loading...  device
module.js:457
    throw err;
    ^

Error: Cannot find module 'pi-wifi'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/matrix-os/lib/device/wifi.js:2:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

**Comment by opogc** [comment]
I fixed uninstalling and reinstalling node js
